### ISSUE TITLE
kill aura and auto 32k do not work well

### ISSUE THREAD

**Issue by Emidio89** [3arthh4ckDevelopment/3arthh4ck-Client#11]
the kill aura doesn't hit behind the wall  after the 3 block range.
the auto 32k crashes as soon as i activate it, please fix this two things.

**Comment by nukiz** [comment]
Send crashlog from the Auto32k crash and also your Killaura config (range is not an issue for me).

**Comment by Emidio89** [comment]
[crash-2023-09-03_16.53.06-client.txt](https://github.com/3arthh4ckDevelopment/3arthh4ck-Client/files/12507152/crash-2023-09-03_16.53.06-client.txt)

**Comment by Emidio89** [comment]
this is the kill aura config
 "KillAura": {
    "Entity": "false",
    "Enemies": "true",
    "Move-Teleport": "false",
    "While-Eating": "true",
    "Render": "false",
    "CPS": "20.0",
    "Teleport": "None",
    "Delay": "true",
    "Name": "KillAura",
    "Vehicles": "false",
    "TP-SetPos": "false",
    "Boss": "false",
    "Swing": "Full",
    "Hidden": "Visible",
    "AutoBlock": "true",
    "Color": "FFFFFFFF-false-false-false-100.0-100.0-100.0",
    "Release-Sprint": "true",
    "Range": "6.0",
    "Passengers": "false",
    "Monsters": "true",
    "Efficient": "false",
    "Fast-32ks": "true",
    "WallRange": "6.0",
    "Rotate": "true",
    "Cooldown": "0",
    "AutoSwitch": "None",
    "Target": "Closest",
    "Target-Range": "10.0",
    "TP-Info": "false",
    "NoEntityEquipment": "false",
    "Armor": "0",
    "Multi-32k": "false",
    "Packets": "1",
    "Toggle": "Normal",
    "Height": "1.0",
    "TP-Range": "0.0",
    "Stay": "false",
    "Players": "true",
    "Rotation-Ticks": "0",
    "Health": "0.0",
    "Y-Teleport": "false",
    "TPS-Sync": "true",
    "Enabled": "true",
    "Hold-Mouse": "false",
    "Soft": "180.0",
    "Riding-Teleports": "false",
    "Render-Mode": "None",
    "Animals": "true",
    "Sword/Axe": "false",
    "Release-Sneak": "true",
    "TamedMobs": "false",
    "Other": "false"

**Comment by nukiz** [comment]
If possible send a video of the Killaura issue and also send the build you're currently using.

**Comment by Emidio89** [comment]
the video is too big and where i can see what build i am using? i am using the latest version of forge (14.23.5.2860)

**Comment by nukiz** [comment]
Send the .jar somewhere via an upload service (preferrably, i don't think you can attach executables in GitHub comments), you can upload the video in YouTube or Streamable.com.

**Comment by Emidio89** [comment]
https://github.com/3arthh4ckDevelopment/3arthh4ck-Client/assets/143833583/4c9fa1a9-ed06-4bee-a8ee-7665441cecb9

this is the clip of the kill aura

**Comment by Emidio89** [comment]
https://ufile.io/ipi0ckfm this is the build if i understand correctly (sorry i dont speak very well english)

**Comment by Emidio89** [comment]
im sorry to bother you, any update?

**Comment by Ai2473** [comment]
the auto32k module in the client shouldn't be used anymore (use the one in the plugin)

**Comment by Emidio89** [comment]
thank you very much

**Comment by Emidio89** [comment]
i am Sorry again but i with the kill aura? Is there anything i can do to fix the hit behind the walls?
