### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GurteX** [3arthh4ckDevelopment/3arthh4ck-Client#13]
**Describe the bug**  
The client is overall terrible

**To Reproduce**  
Install the latest release
Install forge
Put the .jar file in your .minecraft/mods folder
Run forge

**Expected behavior**  
A clear and concise description of what you expected to happen. If your bug is a crash or something you don't need to fill this in.
Barely working, poor code quality

**Crashlog**  
If you crashed and you don't provide a crashlog I will ignore you!

**Additional context**  
It sucks

**Checklist**
- [ ] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

**Comment by nukiz** [comment]
Ok, the client will be deleted within the next 48 hours.

**Comment by nukiz** [comment]
Ok, the client will be deleted within the next 48 hours.

**Comment by GurteX** [comment]
thanks
