### ISSUE TITLE
[FEATURE] Add NameTags See Effects Players

### ISSUE THREAD

**Issue by NCPUser** [3arthh4ckDevelopment/3arthh4ck-Client#14]
Is good for checks illegals effects on players.

**Comment by aidr0b** [comment]
i think sepukku or wwe had something like this 
![image](https://github.com/3arthh4ckDevelopment/3arthh4ck-Client/assets/81508141/94a32ccd-fc4c-49b6-92d5-1715c674bef9)

**Comment by Ai2473** [comment]
Should this be an hud module?

**Comment by aidr0b** [comment]
> Should this be an hud module?

what I send was a hud element, but for illegal check I would say nametags.
