### ISSUE TITLE
[BUG] Steps are glitchy on strict.2b2tpvp.org

### ISSUE THREAD

**Issue by Penguin114** [3arthh4ckDevelopment/3arthh4ck-Client#16]
Step works but lags back on strict.2b2tpvp.org, this did not happen on earthhack 1.8.5

1. log on to strict.2b2tpvp.org
2. turn on step
3. config: 
mode: slow
height: 1.07
use timer: false
timer: 0.95
entity step: false
auto off: false
lag time: 37
mine-gapple: true
compatibility: true
4. try to step up a few blocks, the first time usually works but rest of the times it lags back one time everytime you step. I've checked and im pretty sure it's not a config issue

Without the bug, the step should work without any lagback on strict server like step on earthhack 1.8.5

- [x] I know how to properly use check boxes.
- [x] I have included logs, screenshots, exceptions and / or steps to reproduce the issue.
- [x] I followed the issue template.

**Comment by nukiz** [comment]
Use build https://github.com/3arthh4ckDevelopment/3arthh4ck-Client/actions/runs/6732545754 and enable Step - Offsets - Old. Open a new issue if this still persists, atleast from my testing this worked fine on 2b2tpvp.
