### ISSUE TITLE
i cant join 5b5t/2b2t clone server

### ISSUE THREAD

**Issue by zenngit1234** [3arthh4ckDevelopment/3arthh4ck-Client#21]
I've installed 3arth4ck, but I can't join 5b5t or any other 2b2t clone server because it says not authencated with minecraft.net. Also, if you remove 3arthh4ck from the mods folder, you will be able to participate in 5b5t and 2b2t clones. (I'm Japan, so I used the translation

**Comment by Ai2473** [comment]
Do you have the AccountSpoof module enabled?

**Comment by zenngit1234** [comment]
no

**Comment by zenngit1234** [comment]
wait it tuned on

**Comment by zenngit1234** [comment]
accountspoof is on

**Comment by zenngit1234** [comment]
i toggled off

**Comment by zenngit1234** [comment]
wow i can joined

**Comment by zenngit1234** [comment]
thank you
