### ISSUE TITLE
update

### ISSUE THREAD

**Issue by younojj** [3arthh4ckDevelopment/3arthh4ck-Client#23]
This cheat client is strong but I can't use it because 2b2t is in 1.20.1 but this client is 1.12.2

**Comment by nukiz** [comment]
1.20.4 available soon, grim wont be prioritized though

**Comment by younojj** [comment]
meteor client is really ban, I have never won!

**Comment by younojj** [comment]
Meteor client is really bad, I have never won!

**Comment by nukiz** [comment]
aight dawg
