### ISSUE TITLE
[FEATURE] A lot of cool features to add on 3arthh4ck 1.8.9 and more

### ISSUE THREAD

**Issue by Joao0464** [3arthh4ckDevelopment/3arthh4ck-Client#5]
1. FutureClient AutoCrystal debug option
Ex: 
![autocrystal](https://github.com/3arthh4ckDevelopment/3arthh4ck-Client/assets/115934609/fc28ba37-1863-449d-9697-f58571d9f8fd)
Adding this would be interesting as it only shows the name of the player nearby in the autocrystal
2. 1.19.4/1.20.1 Update on 3arthh4ck (Most of the anarchy servers like 2B2T (not anarchy anymore lol), 8B8T and more are already or will be moving to 1.19.4 and newer current versions, so if possible, adding this would be essential)
3. ChestSwap (instantly change body armor to elytra)
4. ChorusControl (tweaks for Chorus Fruit)
5. NoBob (better viewbobbing on main/off hand)
6. AirPlace (place blocks on air)
7. BookBot

**Comment by nukiz** [comment]
ChorusControl is already implemented, if you don't have it you can use AntiPacket > SPacketPlayerPosLook and Lag-o-Meter.

You can just use BookBot from ForgeHax (it's not too useful so I think it'd be bloat), I'm also pretty confident AirPlace is also implemented (look in BlockTweaks or Reach, if this is a thing)

1.20 is planned, till then use ViaForge.

**Comment by xyzbtw** [comment]
ChestSwap (instantly change body armor to elytra) can be done using a macro and autoarmor modes
NoBob (better viewbobbing on main/off hand) literally go into minecraft settings bro

**Comment by nukiz** [comment]
Some stuff will be implemented, some stuff won't as its bloated.
